import { PARAMETER_TRANSLATION_KEYS } from '@/language/node-parameters.keys';
import { ModelNodeType } from '@/components/Recipe/FlowGraph';
import { ParameterTranslationConfig, SharedTranlsations } from './parameters.types';

export const PARAMETER_TRANSLATIONS_CONFIG: {
  custommodelV2: {
    [K in ModelNodeType]: {
      [k: string]: ParameterTranslationConfig;
    };
  };
  muxv2: {
    [k: string]: ParameterTranslationConfig;
  };
  shared: {
    [k in SharedTranlsations]: ParameterTranslationConfig;
  };
} = {
  custommodelV2: {
    minimax_image01: {
      number_of_images: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.MINIMAX_IMAGE01.NUMBER_OF_IMAGES.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.MINIMAX_IMAGE01.NUMBER_OF_IMAGES.DESCRIPTION,
      },
      aspect_ratio: {
        titleKey: PARAMETER_TRANSLATION_KEYS.SHARED.ASPECT_RATIO.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.MINIMAX_IMAGE01.ASPECT_RATIO.DESCRIPTION,
      },
      prompt_optimizer: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.MINIMAX_IMAGE01.PROMPT_OPTIMIZER.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.MINIMAX_IMAGE01.PROMPT_OPTIMIZER.DESCRIPTION,
      },
    },
    reve: {
      aspect_ratio: {
        titleKey: PARAMETER_TRANSLATION_KEYS.SHARED.ASPECT_RATIO.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.REVE.ASPECT_RATIO.DESCRIPTION,
      },
    },
    imagen3: {
      aspect_ratio: {
        titleKey: PARAMETER_TRANSLATION_KEYS.SHARED.ASPECT_RATIO.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.IMAGEN3.ASPECT_RATIO.DESCRIPTION,
      },
      safety_filter_level: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.IMAGEN3.SAFETY_FILTER_LEVEL.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.IMAGEN3.SAFETY_FILTER_LEVEL.DESCRIPTION,
      },
    },
    wan_video: {
      aspect_ratio: {
        titleKey: PARAMETER_TRANSLATION_KEYS.SHARED.ASPECT_RATIO.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.WAN_VIDEO.ASPECT_RATIO.DESCRIPTION,
      },
      frame_num: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.WAN_VIDEO.FRAME_NUM.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.WAN_VIDEO.FRAME_NUM.DESCRIPTION,
      },
      resolution: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.WAN_VIDEO.RESOLUTION.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.WAN_VIDEO.RESOLUTION.DESCRIPTION,
      },
      sample_steps: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.WAN_VIDEO.SAMPLE_STEPS.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.WAN_VIDEO.SAMPLE_STEPS.DESCRIPTION,
      },
      sample_guide_scale: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.WAN_VIDEO.SAMPLE_GUIDE_SCALE.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.WAN_VIDEO.SAMPLE_GUIDE_SCALE.DESCRIPTION,
      },
      sample_shift: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.WAN_VIDEO.SAMPLE_SHIFT.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.WAN_VIDEO.SAMPLE_SHIFT.DESCRIPTION,
      },
    },
    br_bgreplace: {
      fast: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.BR_BGREPLACE.FAST.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.BR_BGREPLACE.FAST.DESCRIPTION,
      },
      refine_prompt: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.BR_BGREPLACE.REFINE_PROMPT.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.BR_BGREPLACE.REFINE_PROMPT.DESCRIPTION,
      },
      original_quality: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.BR_BGREPLACE.ORIGINAL_QUALITY.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.BR_BGREPLACE.ORIGINAL_QUALITY.DESCRIPTION,
      },
    },
    luma_photon: {
      aspect_ratio: {
        titleKey: PARAMETER_TRANSLATION_KEYS.SHARED.ASPECT_RATIO.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.LUMA_PHOTON.ASPECT_RATIO.DESCRIPTION,
      },
      image_reference_weight: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.LUMA_PHOTON.IMAGE_REFERENCE_WEIGHT.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.LUMA_PHOTON.IMAGE_REFERENCE_WEIGHT.DESCRIPTION,
      },
      style_reference_weight: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.LUMA_PHOTON.STYLE_REFERENCE_WEIGHT.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.LUMA_PHOTON.STYLE_REFERENCE_WEIGHT.DESCRIPTION,
      },
    },
    sd_sketch: {
      control_strength: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.SD_SKETCH.CONTROL_STRENGTH.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.SD_SKETCH.CONTROL_STRENGTH.DESCRIPTION,
      },
      control_type: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.SD_SKETCH.CONTROL_TYPE.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.SD_SKETCH.CONTROL_TYPE.DESCRIPTION,
      },
    },
    minimax_video_director: {
      prompt_optimizer: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.MINIMAX_VIDEO_DIRECTOR.PROMPT_OPTIMIZER.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.MINIMAX_VIDEO_DIRECTOR.PROMPT_OPTIMIZER.DESCRIPTION,
      },
    },
    hunyuan3_d: {
      steps: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.HUNYUAN3D.STEPS.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.HUNYUAN3D.STEPS.DESCRIPTION,
      },
      guidance_scale: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.HUNYUAN3D.GUIDANCE_SCALE.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.HUNYUAN3D.GUIDANCE_SCALE.DESCRIPTION,
      },
      randomize_seed: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.HUNYUAN3D.RANDOMIZE_SEED.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.HUNYUAN3D.RANDOMIZE_SEED.DESCRIPTION,
      },
      octree_resolution: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.HUNYUAN3D.OCTREE_RESOLUTION.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.HUNYUAN3D.OCTREE_RESOLUTION.DESCRIPTION,
      },
      remove_background: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.HUNYUAN3D.REMOVE_BACKGROUND.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.HUNYUAN3D.REMOVE_BACKGROUND.DESCRIPTION,
      },
      num_chunks: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.HUNYUAN3D.NUM_CHUNKS.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.HUNYUAN3D.NUM_CHUNKS.DESCRIPTION,
      },
      target_face_num: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.HUNYUAN3D.TARGET_FACE_NUM.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.HUNYUAN3D.TARGET_FACE_NUM.DESCRIPTION,
      },
    },
    dalle3: {},
    meshy: {
      surface_mode: {
        titleKey: PARAMETER_TRANSLATION_KEYS.MODELS.MESHY.SURFACE_MODE.TITLE,
        descriptionKey: PARAMETER_TRANSLATION_KEYS.MODELS.MESHY.SURFACE_MODE.DESCRIPTION,
      },
    },
  },
  muxv2: {
    options: {
      titleKey: PARAMETER_TRANSLATION_KEYS.MUXV2.OPTIONS.TITLE,
      descriptionKey: PARAMETER_TRANSLATION_KEYS.MUXV2.OPTIONS.DESCRIPTION,
    },
  },
  shared: {
    seed: {
      titleKey: PARAMETER_TRANSLATION_KEYS.SHARED.SEED.TITLE,
      descriptionKey: PARAMETER_TRANSLATION_KEYS.SHARED.SEED.DESCRIPTION,
    },
  },
};
