// FF stands for Feature Flag
export const FF_HIBOB_FONTS = 'hibob-fonts'; // DO NOT REMOVE
export const FF_MAAR_FONTS = 'maar-fonts'; // DO NOT REMOVE
export const FF_KEY_NAVIGATION = 'key-navigation';
export const FF_DESCOPE_AUTH = 'descope-auth';
export const FF_ALEPH_FONTS = 'aleph-fonts'; // DO NOT REMOVE
export const FF_RAKUTEN_FONTS = 'rakuten-fonts'; // DO NOT REMOVE
export const FF_SCRIBOS_FONTS = 'scribos-fonts'; // DO NOT REMOVE
export const FF_DEPOSCO_FONTS = 'deposco-fonts'; // DO NOT REMOVE
export const FF_BARKBOX_FONTS = 'barkbox-fonts'; // DO NOT REMOVE
export const FF_TEXT_ITERATOR = 'text-iterator';
export const FF_NODE_GROUPING = 'node-grouping';
export const FF_CLIENT_OLD_VERSION_RELOAD = 'client-old-version-reload'; // DO NOT REMOVE
export const FF_DALLE3_V2 = 'dalle3-on-new-architecture';
export const FF_MINIMAX_V2 = 'minimax-on-new-architecture';
export const FF_REVE_V2 = 'reve-on-new-architecture';
export const FF_IMAGEN3_V2 = 'imagen3-on-new-architecture';
export const FF_WAN_VIDEO_V2 = 'wan-video-on-new-architecture';
export const FF_BR_BGREPLACE_V2 = 'br-bgreplace-on-new-architecture';
export const FF_SD_SKETCH_V2 = 'sd-sketch-on-new-architecture';
export const FF_MINIMAX_VIDEO_DIRECTOR_V2 = 'minimax-video-director-on-new-architecture';
export const FF_SOCKET_RECONNECTION_ISSUE = 'socket-reconnection-issue';
export const FF_LOG_SOCKET_EVENTS = 'log-socket-events'; // DO NOT REMOVE
export const FF_IMAGE_ITERATOR = 'image-iterator-node';
export const FF_SWIPE_TO_DELETE_EDGE = 'swipe-to-delete-edge';
export const FF_PROXIMITY_CONNECT = 'proximity-connect';
export const FF_PAINTER_NODE = 'painter-node-reimplementation';
export const FF_NODE_GRID_VIEW = 'node-grid-view';
export const FF_LUMA_PHOTON = 'luma-photon-on-new-architecture';
export const FF_MESHY = 'meshy-on-new-architecture';
export const FF_HUNYUAN3D_V2 = 'hunyuan3d-on-new-architecture';
